熟练使用字典和zip函数对numpy数据(X,Y)，依据标签进行分类存储，并最终使用vstack转回numpy格式
运用vstack把列表内的array进行axis=0方向的拼接，然后使用mean和var函数获得参数构建对应的高斯分布
scipy的stats模块中norm函数

离散数据和连续数据分别对应不同的随机分布


In [111]:
import numpy as np
from collections import Counter
import random
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.utils import shuffle
import pandas as pd

In [112]:
iris = load_iris()
X,Y = iris.data,iris.target
X,Y = shuffle(X,Y,random_state=11)

In [113]:
X = X.astype(np.float32)
offset = int(X.shape[0]*0.9)
# 训练集
X_train, Y_train = X[:offset], Y[:offset]
# 测试集
X_test, Y_test = X[offset:], Y[offset:]
Y_train = Y_train.reshape((-1,1))
Y_test = Y_test.reshape((-1,1))

print('X_train ', X_train.shape)
print('X_test ', X_test.shape)
print('Y_train ', Y_train.shape)
print('Y_test ', Y_test.shape)

X_train  (135, 4)
X_test  (15, 4)
Y_train  (135, 1)
Y_test  (15, 1)


In [114]:
for i in zip(X_test,Y_test):
    print(i)

(array([7.2, 3. , 5.8, 1.6], dtype=float32), array([2]))
(array([4.9, 3.1, 1.5, 0.2], dtype=float32), array([0]))
(array([6.4, 2.8, 5.6, 2.2], dtype=float32), array([2]))
(array([7.2, 3.2, 6. , 1.8], dtype=float32), array([2]))
(array([4.8, 3. , 1.4, 0.3], dtype=float32), array([0]))
(array([5.8, 2.6, 4. , 1.2], dtype=float32), array([1]))
(array([7.2, 3.6, 6.1, 2.5], dtype=float32), array([2]))
(array([4.8, 3.4, 1.9, 0.2], dtype=float32), array([0]))
(array([5.8, 2.7, 3.9, 1.2], dtype=float32), array([1]))
(array([6.1, 2.8, 4. , 1.3], dtype=float32), array([1]))
(array([6.8, 2.8, 4.8, 1.4], dtype=float32), array([1]))
(array([4.3, 3. , 1.1, 0.1], dtype=float32), array([0]))
(array([5.5, 2.4, 3.7, 1. ], dtype=float32), array([1]))
(array([6.1, 3. , 4.6, 1.4], dtype=float32), array([1]))
(array([5.5, 2.4, 3.8, 1.1], dtype=float32), array([1]))


In [115]:
Y_label = Y_train.flatten()
cnt = Counter(Y_label)
cnt

Counter({2: 46, 1: 43, 0: 46})

In [116]:
# 计算先验概率
prior_dict = {label: 1 for label in labels}
for label in labels:
    prior_dict[label]=cnt[label]/len(Y_train.flatten())
prior_dict    

{0: 0.34074074074074073, 1: 0.31851851851851853, 2: 0.34074074074074073}

In [117]:
labels = list(set(Y_train.flatten()))
labels

[0, 1, 2]

In [118]:
#新建字典 根据label把相应的x存入对应的key
data = {label: [] for label in labels}
for f, label in zip(X_train, Y_train.flatten()):
    data[label].append(f)
data

{0: [array([4.9, 3.1, 1.5, 0.1], dtype=float32),
  array([5.7, 4.4, 1.5, 0.4], dtype=float32),
  array([4.8, 3.1, 1.6, 0.2], dtype=float32),
  array([4.5, 2.3, 1.3, 0.3], dtype=float32),
  array([4.7, 3.2, 1.3, 0.2], dtype=float32),
  array([4.6, 3.6, 1. , 0.2], dtype=float32),
  array([4.8, 3. , 1.4, 0.1], dtype=float32),
  array([4.8, 3.4, 1.6, 0.2], dtype=float32),
  array([5.4, 3.9, 1.3, 0.4], dtype=float32),
  array([5.1, 3.5, 1.4, 0.2], dtype=float32),
  array([5. , 3.3, 1.4, 0.2], dtype=float32),
  array([4.7, 3.2, 1.6, 0.2], dtype=float32),
  array([5.5, 3.5, 1.3, 0.2], dtype=float32),
  array([4.6, 3.4, 1.4, 0.3], dtype=float32),
  array([5. , 3.2, 1.2, 0.2], dtype=float32),
  array([5.1, 3.8, 1.6, 0.2], dtype=float32),
  array([4.4, 3.2, 1.3, 0.2], dtype=float32),
  array([5.4, 3.4, 1.7, 0.2], dtype=float32),
  array([5.1, 3.7, 1.5, 0.4], dtype=float32),
  array([5. , 3.4, 1.6, 0.4], dtype=float32),
  array([5.2, 3.4, 1.4, 0.2], dtype=float32),
  array([5. , 3.6, 1.4, 0.2], d

In [119]:
mean_dict = {label: [] for label in labels}
var_dict = {label: [] for label in labels}
for label in labels:
    mean_dict[label]=np.vstack(data[label]).mean(axis=0)
    var_dict[label]=np.vstack(data[label]).var(axis=0)

In [120]:
mean_dict

{0: array([5.0326085 , 3.454348  , 1.4608697 , 0.24999996], dtype=float32),
 1: array([5.934883 , 2.7860465, 4.2837214, 1.3418604], dtype=float32),
 2: array([6.5521736, 2.958696 , 5.5239134, 2.0260873], dtype=float32)}

In [121]:
var_dict

{0: array([0.11871926, 0.14204633, 0.02499056, 0.01119565], dtype=float32),
 1: array([0.2752947 , 0.10352623, 0.22322336, 0.03964303], dtype=float32),
 2: array([0.40423432, 0.1002505 , 0.31138477, 0.06975426], dtype=float32)}

In [122]:
def predict(X):
    y = np.array([-1]*X.shape[0])
    for row in range(X.shape[0]):
        x = X[row,:]
        probability = {label: 1 for label in labels}
        for i in range(len(x)):
            for label in labels:
                probability[label] = probability[label] * prior_dict[label] * stats.norm(mean_dict[label][i],var_dict[label][i]).pdf(x[i])
        # print(probability)
        y[row]=max(probability,key=probability.get)
    return y

In [123]:
Y_pred = predict(X_test)

In [124]:
Y_pred

array([2, 0, 2, 2, 0, 1, 2, 0, 1, 1, 1, 0, 1, 1, 1])

In [125]:
Y_test.flatten()

array([2, 0, 2, 2, 0, 1, 2, 0, 1, 1, 1, 0, 1, 1, 1])

In [126]:
count=0
for i in range(len(Y_pred)):
    if Y_pred[i]==Y_test.flatten()[i]:
        count = count+1
print(count)
print(count/len(Y_pred))

15
1.0
